# SOC = separetion of concerns
### Read all users
GET http://localhost:3050/api/v2/users

### Create test a new user

POST http://localhost:3050/api/v2/users
Content-Type: application/json

{
    "username":"Chris",
    "email": "chris@example.com",
    "password": "456789123"
}

### Update a user

PUT http://localhost:3050/api/v2/users/6a0be230af5da4776a1d41a1
Content-Type: application/json

{
    "username":"Christopher",
    "email": "chris.j@example.com",
    "password": "555555555"
}

### Delete a user
DELETE http://localhost:3050/api/v2/users/6a06cdcc4e5c5c51d2e49087